# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: WilhelmHappe.PDFlight
PackageVersion: 1.1.0
InstallerType: inno
Scope: machine
UpgradeBehavior: install
FileExtensions:
- pdf
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.DotNet.DesktopRuntime.10
ProductCode: '{7E1B0A4C-5A34-4B7A-9C57-3D8A41C6F2B9}_is1'
Installers:
- Architecture: x64
  InstallerUrl: https://www.netradio.info/download/PDFlightSetup.exe
  InstallerSha256: 0B6844E1B234A606CC731E4C3B7D14E693AF7D1E5C06D15E73336D7A8659BB69
ManifestType: installer
ManifestVersion: 1.9.0
